### ISSUE TITLE
How about a screenshot?

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [melanholly/qt5-led-indicator-widget#1]
I would like to see, how the widget looks, before trying to download / compile / integrate into existing projects.

Please add a screenshot to the README.md

**Comment by melanholly** [comment]
I will add one tomorow

**Comment by melanholly** [comment]
There it one. It is from the repository project file.
![Screenshot](https://user-images.githubusercontent.com/1505809/31757257-d6999286-b4b0-11e7-8031-f799577a6685.png)
It is added to README.md
